// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 9000000 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int clp_interapp_receive_9000000 = 9000000;
	/// <summary>PID: 9000000 | Type: read</summary>
	public const int clp_interapp_receive = 9000000;
	/// <summary>PID: 9000001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int clp_interapp_return_9000001 = 9000001;
	/// <summary>PID: 9000001 | Type: read</summary>
	public const int clp_interapp_return = 9000001;
	public class Write
	{
		/// <summary>PID: 990 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int persons_contextmenu_990 = 990;
		/// <summary>PID: 990 | Type: write</summary>
		public const int persons_contextmenu = 990;
	}
	public class Persons
	{
		/// <summary>PID: 1000</summary>
		public const int tablePid = 1000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1001</summary>
		public const int indexColumnPid = 1001;
		public class Pid
		{
			/// <summary>PID: 1001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsindex_1001 = 1001;
			/// <summary>PID: 1001 | Type: read</summary>
			public const int personsindex = 1001;
			/// <summary>PID: 1002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsfirstname_1002 = 1002;
			/// <summary>PID: 1002 | Type: read</summary>
			public const int personsfirstname = 1002;
			/// <summary>PID: 1003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personslastname_1003 = 1003;
			/// <summary>PID: 1003 | Type: read</summary>
			public const int personslastname = 1003;
			/// <summary>PID: 1004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsgender_1004 = 1004;
			/// <summary>PID: 1004 | Type: read</summary>
			public const int personsgender = 1004;
			/// <summary>PID: 1005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsage_1005 = 1005;
			/// <summary>PID: 1005 | Type: read</summary>
			public const int personsage = 1005;
			/// <summary>PID: 1006 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsdisplaykey_1006 = 1006;
			/// <summary>PID: 1006 | Type: read</summary>
			public const int personsdisplaykey = 1006;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsindex_1001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int personsindex = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsfirstname_1002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int personsfirstname = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personslastname_1003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int personslastname = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsgender_1004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int personsgender = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsage_1005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int personsage = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int personsdisplaykey_1006 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int personsdisplaykey = 5;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 990  | Type: write | DISCREETS: Add item... = 1001, Separator 1 = -1, Edit item... = 1002, Separator 2 = -2, Delete selected item(s) = 1003</summary>
	public System.Object Persons_contextmenu {get { return Protocol.GetParameter(990); }set { Protocol.SetParameter(990, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 1000</summary>
	PersonsQActionTable persons { get; set; }
	object Afterstartup_dummy { get; set; }
	object Persons_contextmenu_990 { get; set; }
	object Persons_contextmenu { get; set; }
	object Personsindex_1001 { get; set; }
	object Personsindex { get; set; }
	object Personsfirstname_1002 { get; set; }
	object Personsfirstname { get; set; }
	object Personslastname_1003 { get; set; }
	object Personslastname { get; set; }
	object Personsgender_1004 { get; set; }
	object Personsgender { get; set; }
	object Personsage_1005 { get; set; }
	object Personsage { get; set; }
	object Personsdisplaykey_1006 { get; set; }
	object Personsdisplaykey { get; set; }
	object Clp_interapp_receive_9000000 { get; set; }
	object Clp_interapp_receive { get; set; }
	object Clp_interapp_return_9000001 { get; set; }
	object Clp_interapp_return { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1000</summary>
	public PersonsQActionTable persons { get; set; }
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 990  | Type: write | DISCREETS: Add item... = 1001, Separator 1 = -1, Edit item... = 1002, Separator 2 = -2, Delete selected item(s) = 1003</summary>
	public System.Object Persons_contextmenu_990 {get { return GetParameter(990); }set { SetParameter(990, value); }}
	/// <summary>PID: 990  | Type: write | DISCREETS: Add item... = 1001, Separator 1 = -1, Edit item... = 1002, Separator 2 = -2, Delete selected item(s) = 1003</summary>
	public System.Object Persons_contextmenu {get { return Write.Persons_contextmenu; }set { Write.Persons_contextmenu = value; }}
	/// <summary>PID: 1001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsindex_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	public System.Object Personsindex {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsfirstname_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Personsfirstname {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personslastname_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	public System.Object Personslastname {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Male = M, Female = F, X = X</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsgender_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Male = M, Female = F, X = X</summary>
	public System.Object Personsgender {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsage_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	public System.Object Personsage {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1006  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsdisplaykey_1006 {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 1006  | Type: read</summary>
	public System.Object Personsdisplaykey {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 9000000  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clp_interapp_receive_9000000 {get { return GetParameter(9000000); }set { SetParameter(9000000, value); }}
	/// <summary>PID: 9000000  | Type: read</summary>
	public System.Object Clp_interapp_receive {get { return GetParameter(9000000); }set { SetParameter(9000000, value); }}
	/// <summary>PID: 9000001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Clp_interapp_return_9000001 {get { return GetParameter(9000001); }set { SetParameter(9000001, value); }}
	/// <summary>PID: 9000001  | Type: read</summary>
	public System.Object Clp_interapp_return {get { return GetParameter(9000001); }set { SetParameter(9000001, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		persons = new PersonsQActionTable(this, 1000, "persons");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class PersonsQActionTable : QActionTable, IEnumerable<PersonsQActionRow>
{
	public PersonsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<PersonsQActionRow> GetEnumerator() { return new QActionTableEnumerator<PersonsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class PersonsQActionRow : QActionTableRow
{
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsindex_1001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1001 | Type: read</summary>
	public System.Object Personsindex { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsfirstname_1002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	public System.Object Personsfirstname { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personslastname_1003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	public System.Object Personslastname { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsgender_1004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	public System.Object Personsgender { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsage_1005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	public System.Object Personsage { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1006 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Personsdisplaykey_1006 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 1006 | Type: read</summary>
	public System.Object Personsdisplaykey { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	public PersonsQActionRow() : base(0, 6) { }
	public PersonsQActionRow(System.Object[] oRow) : base(0, 6, oRow) { }
	public static implicit operator PersonsQActionRow(System.Object[] source) { return new PersonsQActionRow(source); }
	public static implicit operator System.Object[](PersonsQActionRow source) { return source.ToObjectArray(); }
}
}
